language: node_js
node_js:
  - "0.8"
  - "0.9"
  - "0.10"
branches:
  only:
    - master
    - minver
before_script:
  - git clone git://github.com/visionmedia/node-jscoverage.git
  - cd node-jscoverage
  - ./configure
  - make
  - cd ..
