language: node_js
node_js:
  - '0.10'
branches:
  only:
    - master
deploy:
  provider: npm
  email: jakob.mattsson@gmail.com
  skip_cleanup: true
  api_key:
    secure: 0OZbrk6kFdWpMNpMFgH+kAk6N29fp0xeUFy2PyCz6aiGkARKCwdmrGpQBGprWeYzE+AxB1ONslEgztxF9lT/YGkenro4EHFJuHFT10CNUSrb0L12H7dAsq0XX50IrmaFayYyjM+zMx12VFMyV7vbDHgJz9shEY9GGhf6jcSOb3c=
  on:
    tags: true
    branch: master
    repo: jakobmattsson/jscov
before_script:
  - git clone git://github.com/visionmedia/node-jscoverage.git
  - cd node-jscoverage
  - ./configure
  - make
  - cd ..
notifications:
  hipchat:
    rooms:
      secure: Qvhy3+L0ZCyQrqt+n6edGMF6dpZ3xD52w5ETciBR/+f8h8cOCf7ymLWEozMcPCZhMgDZsNgH9qrtURFJo7ziP6164N+vHffXjFBAm7voGUCYWtKkLwljCecr8W+AeZ/tUeGOZSXgGSMlLQlk53NMtW0ZHzwLS1Zr18JEbGvmIWE=
