language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: jakob.mattsson@gmail.com
  skip_cleanup: true
  api_key:
    secure: XYWkWt2IAFT4qcZpb+UThY4LZiUzqXUC58vUq0CZ6/fVt0Bd6G7J4sMdDFmCEvxEiPDiWWvCBI2NvIdywIA3pnpA1UWpkbNbm4Vz4/8DU3Q5zc6MD6wA1lqGDEyYAKt999jizMSRd7UBGkHJvetph/JTgo+aSk6BXR9nAmUwnx4=
  on:
    tags: true
    branch: master
    repo: jakobmattsson/jscov
notifications:
  email:
    on_success: never
    on_failure: always
  hipchat:
    rooms:
      secure: CX+Y2Pw3y/x/da+WbtOnrIT2FubHGA8EBT6s6UcMQw0Abgzy+NRPSVpGdMN+FrPiHTtlYaWS0i/6wsO1CpVOtkHIKPhGXFZMQOV2scajl6NyUq2arUzzxf4JK6Dr+1v3Db4GyMqYQdYNQEBW+r0Kl99fvAWMg4Fxwe+mcpaQXkk=
    template:
    - ! '%{repository}#%{build_number} (%{branch} - %{commit} - %{author}): %{message}

      Change view: %{compare_url}

      Build details: %{build_url}'
before_script:
- git clone git://github.com/visionmedia/node-jscoverage.git
- cd node-jscoverage
- ./configure
- make
- cd ..
