language: node_js
node_js:
  - '0.10'
branches:
  only:
    - master
deploy:
  provider: npm
  email: jakob.mattsson@gmail.com
  skip_cleanup: true
  api_key:
    secure: HPxPQLEQzCC1lzfHLJ/HfF+6nsOQkchPynslM0daQXSPxEMF2N+qSJkBW414mAEcjfBWISF1cBCnZK308ZQ+zzaSaHM1giRwZoTMR+gdvKkEre0J9984Z4b4MR7xOZnkKFtDZ0UVGLVCC6E7fRTlIaksiePrFA4kH+4bZA46vI8=
  on:
    tags: true
    branch: master
    repo: jakobmattsson/jscov
before_script:
  - git clone git://github.com/visionmedia/node-jscoverage.git
  - cd node-jscoverage
  - ./configure
  - make
  - cd ..
