language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
deploy:
  provider: npm
  email: jakob.mattsson@gmail.com
  skip_cleanup: true
  api_key:
    secure: p3CNpPeoAFuKAqFcfC6FoANm/6jULODvqxyzo3R2YzFiTfsA+u6rtl+orJqY5B4Yn4pNs+CFu29eeYlqBHXArRw0otjkznNh9QI/cDiRIE2LPE9bnw+HjIUd/IabTGdVLI83WjqkFLAgsZvPOKqzVmIcKVJbNUDozVoh7lHoS/0=
  on:
    tags: true
    branch: master
    repo: jakobmattsson/jscov
before_script:
- git clone git://github.com/visionmedia/node-jscoverage.git
- cd node-jscoverage
- ./configure
- make
- cd ..
notifications:
  hipchat:
    rooms:
      secure: CX+Y2Pw3y/x/da+WbtOnrIT2FubHGA8EBT6s6UcMQw0Abgzy+NRPSVpGdMN+FrPiHTtlYaWS0i/6wsO1CpVOtkHIKPhGXFZMQOV2scajl6NyUq2arUzzxf4JK6Dr+1v3Db4GyMqYQdYNQEBW+r0Kl99fvAWMg4Fxwe+mcpaQXkk=
