a['notAKeyword'].f()
a[''].f()

a['break'].f();
a['case'].f();
a['catch'].f();
a['continue'].f();
a['debugger'].f();
a['default'].f();
a['delete'].f();
a['do'].f();
a['else'].f();
a['finally'].f();
a['for'].f();
a['function'].f();
a['if'].f();
a['in'].f();
a['instanceof'].f();
a['new'].f();
a['return'].f();
a['switch'].f();
a['this'].f();
a['throw'].f();
a['try'].f();
a['typeof'].f();
a['var'].f();
a['void'].f();
a['while'].f();
a['with'].f();

a['throws'].f();
